name: Build Custom GeoIP Files

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "LICENSE*"
      - "*.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Build Custom GeoIP
        run: |
          echo "Current directory contents:"
          ls -la
          cat ./config.json || { echo "Failed to read config.json"; exit 1; }
          go build ./
          ./geoip convert -c ./config.json || { echo "Convert failed"; exit 1; }
          echo "Files after conversion:"
          ls -la
          ls -la ./output || { echo "Output directory not found"; exit 1; }
          test -f ./output/blockip.dat || { echo "blockip.dat was not generated"; exit 1; }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: custom-geoip-files
          path: "./output/blockip.dat"

      - name: Generate sha256 checksum for dat files
        run: |
          cd ./output || exit 1
          sha256sum blockip.dat > ./blockip.dat.sha256sum

      - name: Upload files to GitHub release
        uses: actions/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./output/blockip.dat ./output/blockip.dat.sha256sum
          release_name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.TAG_NAME }}
